### ISSUE TITLE
[BUG] Linux Mint - start without GUI 1.6.2 so on

### ISSUE THREAD

**Issue by sazaog** [streetpea/chiaki-ng#291] opened 2024-03-23 11:26 UTC
Hi

I have a problem: all new versions starts and stays in the background as a process but GUi does not start.
1.6.1 working fine, all other version have same issue. I try in VM clear install, all kernals and have same issue.

 OS: Linux Mint 21.3 x86_64
 Host: 20KGSCLJ00 ThinkPad X1 Carbon
 Kernel: 5.15.0-101-generic
 Uptime: 8 mins
 Packages: 2525 (dpkg), 37 (flatpak)
 Shell: bash 5.1.16
 Resolution: 2560x1440
 DE: Cinnamon 6.0.4
 WM: Mutter (Muffin)
 WM Theme: Mint-Y-Dark-Aqua (Mint-Y)
 Theme: Mint-Y-Aqua [GTK2/3]
 Icons: Mint-Y-Aqua [GTK2/3]
 Terminal: gnome-terminal
 CPU: Intel i7-8650U (8) @ 4.200GHz
 GPU: Intel UHD Graphics 620
 Memory: 2107MiB / 15862MiB

**Comment by streetpea** [comment] 2024-03-24 20:19
Run from command line with `flatpak run io.github.streetpea.Chiaki4deck` and post any errors you get.

**Comment by sazaog** [comment] 2024-03-26 17:22
no log in term
![Screenshot from 2024-03-26 18-18-49](https://github.com/streetpea/chiaki4deck/assets/64551588/96e9e1e1-bfd3-4265-a713-fe103841f7b0)

**Comment by streetpea** [comment] 2024-03-27 03:27
That's weird I get logs in the terminal in other Linux distributions I've tried ...

**Comment by sazaog** [comment] 2024-03-27 17:45
yes I know it's weird...when I downgrade to 1.6.1. everything working fine...and log is showing in term.

**Comment by streetpea** [comment] 2024-03-27 18:43
Then possibly it's not even getting far enough to print anything.

**Comment by streetpea** [comment] 2024-03-27 18:45
Can you try the appimage on the releases page and see if it exhibits the same behavior?

**Comment by sazaog** [comment] 2024-03-28 21:29
after start appimage getting 

"tmp/.mount_ChiakiVEJ9tu/AppRun.wrapped: error while loading shared libraries: libhidapi-hidraw.so.0: cannot open shared object file: No such file or directory"

fix
install sudo apt install libhidapi-hidraw0"
app starting fine. 

now question of all question - why flatpak doesn't working after version 1.6.1!?

**Comment by streetpea** [comment] 2024-03-29 00:41
Its quite strange but hard to debug given no logs are being output...

**Comment by streetpea** [comment] 2024-03-29 05:37
@sazaog if you want I can make a flatpak build using the old manifest other than the right commit to make sure it isn’t something in the manifest that was changed.

**Comment by sazaog** [comment] 2024-03-29 22:18
let's give it try with old manifest

**Comment by sazaog** [comment] 2024-03-29 22:20
> after start appimage getting
> 
> "tmp/.mount_ChiakiVEJ9tu/AppRun.wrapped: error while loading shared libraries: libhidapi-hidraw.so.0: cannot open shared object file: No such file or directory"
> 
> fix install sudo apt install libhidapi-hidraw0" app starting fine.
> 
> now question of all question - why flatpak doesn't working after version 1.6.1!?

I didn't try is't working in game :-)..but gui working. Im going on buss trip ill try in 10 days.

**Comment by k9janer** [comment] 2024-04-12 18:23
This bug is also affecting me.

I haven't used Chiaki4Deck before (just the normal Chiaki) and so there were no old settings from an older version present. It works after downgrading to 1.6.1.

Is there any way I can help solve this issue?

```

System:
  Kernel: 6.5.0-27-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 6.0.4 tk: GTK 3.24.33
    wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: ASUSTeK product: Vivobook_ASUSLaptop M3401QA_M3401QA v: 1.0
  Mobo: ASUSTeK model: M3401QA v: 1.0 serial: <superuser required>
    UEFI: American Megatrends LLC. v: M3401QA.308 date: 11/07/2022
CPU:
  Info: 6-core model: AMD Ryzen 5 5600H with Radeon Graphics bits: 64 type: MT MCP smt: enabled
    arch: Zen 3 rev: 0 cache: L1: 384 KiB L2: 3 MiB L3: 16 MiB
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Cezanne vendor: ASUSTeK driver: amdgpu v: kernel pcie: speed: 8 GT/s lanes: 16
    ports: active: eDP-1 empty: HDMI-A-1 bus-ID: 03:00.0 chip-ID: 1002:1638 class-ID: 0300
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 2880x1800 s-dpi: 96 s-size: 762x476mm (30.0x18.7") s-diag: 898mm (35.4")
  Monitor-1: eDP res: 2880x1800 hz: 90 dpi: 242 size: 302x189mm (11.9x7.4") diag: 356mm (14")
  OpenGL: renderer: RENOIR (renoir LLVM 15.0.7 DRM 3.54 6.5.0-27-generic)
    v: 4.6 Mesa 23.2.1-1ubuntu3.1~22.04.2 direct render: Yes
Audio:
  Device-1: AMD Renoir Radeon High Definition Audio driver: snd_hda_intel v: kernel pcie:
    speed: 8 GT/s lanes: 16 bus-ID: 03:00.1 chip-ID: 1002:1637 class-ID: 0403
  Device-2: AMD Raven/Raven2/FireFlight/Renoir Audio Processor vendor: ASUSTeK driver: N/A pcie:
    speed: 8 GT/s lanes: 16 bus-ID: 03:00.5 chip-ID: 1022:15e2 class-ID: 0480
  Device-3: AMD Family 17h HD Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel pcie:
    speed: 8 GT/s lanes: 16 bus-ID: 03:00.6 chip-ID: 1022:15e3 class-ID: 0403
  Sound Server-1: ALSA v: k6.5.0-27-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: MEDIATEK MT7921 802.11ax PCI Express Wireless Network Adapter vendor: AzureWave
    driver: mt7921e v: kernel pcie: speed: 5 GT/s lanes: 1 bus-ID: 01:00.0 chip-ID: 14c3:7961
    class-ID: 0280
  IF: wlp1s0 state: up mac: <filter>
Bluetooth:
  Device-1: IMC Networks Wireless_Device type: USB driver: btusb v: 0.8 bus-ID: 3-2:2
    chip-ID: 13d3:3563 class-ID: e001 serial: <filter>
  Report: hciconfig ID: hci0 rfk-id: 2 state: down bt-service: enabled,running rfk-block:
    hardware: no software: yes address: <filter>
Drives:
  Local Storage: total: 476.94 GiB
  ID-1: /dev/nvme0n1 vendor: Western Digital model: PC SN530 SDBPNPZ-512G-1002 size: 476.94 GiB
    speed: 31.6 Gb/s lanes: 4 type: SSD serial: <filter> rev: 21106000 temp: 29.9 C scheme: GPT
Partition:
  ID-1: / size: 465.29 GiB used: 178.96 GiB (38.5%) fs: ext4 dev: /dev/dm-1 mapped: vgmint-root
  ID-2: /boot size: 1.61 GiB used: 1.24 GiB (77.5%) fs: ext4 dev: /dev/nvme0n1p2
  ID-3: /boot/efi size: 511 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: file size: 32 GiB used: 0 KiB (0.0%) priority: -2 file: /swapfile
  ID-2: swap-2 type: partition size: 980 MiB used: 0 KiB (0.0%) priority: -3 dev: /dev/dm-2
    mapped: vgmint-swap_1
USB:
  Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 4 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Hub-2: 2-0:1 info: Super-speed hub ports: 2 rev: 3.1 speed: 10 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
  Hub-3: 3-0:1 info: Hi-speed hub with single TT ports: 4 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 3-2:2 info: IMC Networks Wireless_Device type: Bluetooth driver: btusb interfaces: 3
    rev: 2.1 speed: 480 Mb/s power: 100mA chip-ID: 13d3:3563 class-ID: e001 serial: <filter>
  Hub-4: 4-0:1 info: Super-speed hub ports: 2 rev: 3.1 speed: 10 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: 34.0 C mobo: N/A gpu: amdgpu temp: 34.0 C
  Fan Speeds (RPM): cpu: 0
Repos:
  Packages: 2521 apt: 2493 flatpak: 28
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/brave-browser-release.list
    1: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https: //brave-browser-apt-release.s3.brave.com/ stable main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com virginia main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
Info:
  Processes: 384 Uptime: 14m wakeups: 38626 Memory: 7.16 GiB used: 3.44 GiB (48.0%) Init: systemd
  v: 249 runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 Client: Cinnamon v: 6.0.4 inxi: 3.3.13


```

**Comment by sazaog** [comment] 2024-04-23 17:43
same issue flatpak and appimage on version 1.6.6.

**Comment by streetpea** [comment] 2024-05-11 21:50
@sazaog what logs do you get in the konsole when you launch via the appimage?

**Comment by k9janer** [comment] 2024-05-12 11:26
Via the appimage version 1.6.6 the console output looks like this:

...

./Chiaki4deck.AppImage
/tmp/.mount_ChiakiVcea1S/AppRun.wrapped: error while loading shared libraries: libhidapi-hidraw.so.0: cannot open shared object file: No such file or directory

...

So after installing libhidapi-hidraw0:

...

./Chiaki4deck.AppImage
chiaki.gui: [libplacebo] Initialized libplacebo v6.338.0-70-gc320f61e-dirty (API v342)
chiaki.gui: [libplacebo] Spent 31,256 ms enumerating instance extensions
chiaki.gui: [libplacebo] Creating vulkan instance with extensions:
chiaki.gui: [libplacebo]     VK_KHR_get_physical_device_properties2
chiaki.gui: [libplacebo]     VK_KHR_surface
chiaki.gui: [libplacebo]     VK_EXT_swapchain_colorspace
chiaki.gui: [libplacebo]     VK_KHR_external_memory_capabilities
chiaki.gui: [libplacebo]     VK_KHR_external_semaphore_capabilities
chiaki.gui: [libplacebo]     VK_KHR_get_surface_capabilities2
chiaki.gui: [libplacebo]     VK_KHR_xcb_surface
chiaki.gui: [libplacebo]     VK_KHR_surface
chiaki.gui: [libplacebo] Probing for vulkan devices:
chiaki.gui: [libplacebo]     GPU 0: AMD Unknown (RADV RENOIR) v1.3.255 (integrated)
chiaki.gui: [libplacebo]            uuid: 00:00:00:00:03:00:00:00:00:00:00:00:00:00:00:00
chiaki.gui: [libplacebo]     GPU 1: llvmpipe (LLVM 15.0.7, 256 bits) v1.3.255 (software)
chiaki.gui: [libplacebo]            uuid: 6D:65:73:61:32:33:2E:32:2E:31:2D:31:75:62:75:00
chiaki.gui: [libplacebo] Vulkan device properties:
chiaki.gui: [libplacebo]     Device Name: AMD Unknown (RADV RENOIR)
chiaki.gui: [libplacebo]     Device ID: 1002:1638
chiaki.gui: [libplacebo]     Device UUID: 00:00:00:00:03:00:00:00:00:00:00:00:00:00:00:00
chiaki.gui: [libplacebo]     Driver version: 5c02001
chiaki.gui: [libplacebo]     API version: 1.3.255
chiaki.gui: [libplacebo] Using async transfer (queue 1)
chiaki.gui: [libplacebo] Using async compute (queue 1)
chiaki.gui: [libplacebo] Creating vulkan device with extensions:
chiaki.gui: [libplacebo]     VK_KHR_swapchain
chiaki.gui: [libplacebo]     VK_KHR_push_descriptor
chiaki.gui: [libplacebo]     VK_KHR_external_memory_fd
chiaki.gui: [libplacebo]     VK_EXT_external_memory_dma_buf
chiaki.gui: [libplacebo]     VK_EXT_external_memory_host
chiaki.gui: [libplacebo]     VK_KHR_external_semaphore_fd
chiaki.gui: [libplacebo]     VK_EXT_pci_bus_info
chiaki.gui: [libplacebo]     VK_EXT_image_drm_format_modifier
chiaki.gui: [libplacebo] Spent 68,639 ms creating vulkan device
chiaki.gui: [libplacebo] Memory heaps supported by device:
chiaki.gui: [libplacebo]     0: flags 0x0 size 1392M
chiaki.gui: [libplacebo]     1: flags 0x1 size 2784M
chiaki.gui: [libplacebo] Memory summary:     0 used     0 res     0 alloc, efficiency 100,00%, utilization 100,00%, max page:  174M
chiaki.gui: [libplacebo] glslang version: 13.1.1
chiaki.gui: [libplacebo] Initialized SPIR-V compiler 'glslang'
chiaki.gui: [libplacebo] GPU information:
chiaki.gui: [libplacebo]     GLSL version: 450 (vulkan)
chiaki.gui: [libplacebo]       max_shmem_size:            65536
chiaki.gui: [libplacebo]       max_group_threads:         1024
chiaki.gui: [libplacebo]       max_group_size[0]:         1024
chiaki.gui: [libplacebo]       max_group_size[1]:         1024
chiaki.gui: [libplacebo]       max_group_size[2]:         1024
chiaki.gui: [libplacebo]       subgroup_size:             64
chiaki.gui: [libplacebo]       min_gather_offset:         -32
chiaki.gui: [libplacebo]       max_gather_offset:         31
chiaki.gui: [libplacebo]     Limits:
chiaki.gui: [libplacebo]       thread_safe:               1
chiaki.gui: [libplacebo]       callbacks:                 1
chiaki.gui: [libplacebo]       max_buf_size:              2919661568
chiaki.gui: [libplacebo]       max_ubo_size:              2919661568
chiaki.gui: [libplacebo]       max_ssbo_size:             2919661568
chiaki.gui: [libplacebo]       max_vbo_size:              2919661568
chiaki.gui: [libplacebo]       max_mapped_size:           2919661568
chiaki.gui: [libplacebo]       max_buffer_texels:         2919661568
chiaki.gui: [libplacebo]       align_host_ptr:            4096
chiaki.gui: [libplacebo]       host_cached:               1
chiaki.gui: [libplacebo]       max_tex_1d_dim:            16384
chiaki.gui: [libplacebo]       max_tex_2d_dim:            16384
chiaki.gui: [libplacebo]       max_tex_3d_dim:            2048
chiaki.gui: [libplacebo]       blittable_1d_3d:           1
chiaki.gui: [libplacebo]       buf_transfer:              1
chiaki.gui: [libplacebo]       align_tex_xfer_pitch:      1
chiaki.gui: [libplacebo]       align_tex_xfer_offset:     4
chiaki.gui: [libplacebo]       max_variable_comps:        0
chiaki.gui: [libplacebo]       max_constants:             18446744073709551615
chiaki.gui: [libplacebo]       max_pushc_size:            256
chiaki.gui: [libplacebo]       align_vertex_stride:       1
chiaki.gui: [libplacebo]       max_dispatch[0]:           65535
chiaki.gui: [libplacebo]       max_dispatch[1]:           65535
chiaki.gui: [libplacebo]       max_dispatch[2]:           65535
chiaki.gui: [libplacebo]       fragment_queues:           1
chiaki.gui: [libplacebo]       compute_queues:            1
chiaki.gui: [libplacebo]     External API interop:
chiaki.gui: [libplacebo]       UUID: 00:00:00:00:03:00:00:00:00:00:00:00:00:00:00:00
chiaki.gui: [libplacebo]       PCI: 0000:03:00:0
chiaki.gui: [libplacebo]       buf export caps: 0x9
chiaki.gui: [libplacebo]       buf import caps: 0x19
chiaki.gui: [libplacebo]       tex export caps: 0x9
chiaki.gui: [libplacebo]       tex import caps: 0x19
chiaki.gui: [libplacebo]       sync export caps: 0x1
chiaki.gui: [libplacebo]       sync import caps: 0x0
chiaki.gui: [libplacebo] Available surface configurations:
chiaki.gui: [libplacebo]     0: VK_FORMAT_B8G8R8A8_SRGB                  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
chiaki.gui: [libplacebo]     1: VK_FORMAT_B8G8R8A8_UNORM                 VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
chiaki.gui: [libplacebo] Picked surface configuration 1: VK_FORMAT_B8G8R8A8_UNORM + VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
chiaki.gui: [libplacebo] Spent 88,354 ms translating SPIR-V

...

The app then opens without any issues.

**Comment by streetpea** [comment] 2024-05-14 18:55
Pipewire is needed for dualsense haptics but other than that everything should work normally with pulse enabled as the SDL_AUDIODRIVER

**Comment by k9janer** [comment] 2024-05-15 16:28
Yes, everything seems to work fine with PulseAudio except for haptics. :) (There are some minimal haptics with Astro's Playroom, for example there is some vibration when pressing the adaptive triggers in the controller demo.)

But Chiaki4Deck not starting without the additional parameter is a bug, right? It seems like it doesn't fall back to PulseAudio automatically/properly.

**Comment by streetpea** [comment] 2024-06-07 19:10
@k9janer I believe pipewire-pulse is the one that's required. I believe in SDL 2 there is no way to check if pipewire is available before trying to use it and when it does try to use it, if it's not there it causes the issue you are describing. I don't believe there is a way around this if we want to use pipewire for most instances unless we switch to SDL 3 which has the ability to check if pipewire is installed and if it isn't falls back to pulse. Having said that, moving to SDL 3 would be a bigger effort that hasn't been done yet as the official release of 3 (3.2.0 https://github.com/libsdl-org/SDL/milestone/10) hasn't happened yet.

**Comment by streetpea** [comment] 2024-09-06 22:47
Closing as the issue is that pipe wire-pulse is required for the appimage without using SDL_AUDIODRIVER=pulse and there doesn't appear to be a way around this with SDL2

**Closed by streetpea** 2024-09-06 22:47 UTC
