### ISSUE TITLE
[BUG] Controller Mapping is not saved

### ISSUE THREAD

**Issue by jaconey** [streetpea/chiaki-ng#420] opened 2024-09-28 22:24 UTC
**Describe the bug**
Controller Mapping is not saved

**Debug Log**
No log produced

**To Reproduce**
1. Open "Controllers"
2. Change Controller Mapping
3. Change some buttons
4. Update Controller Mapping
5. Kill the app and restart it
6. Controller mapping is reset to default

**Expected behavior**
It should keep the mapping

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Macosx 
 - Version 15.0
 - Device 8bitdo Pro 2 BT controller
 - chiaki-ng Version 1.9.0

**Comment by streetpea** [comment] 2024-09-28 22:27
Did you apply the controller mapping. Can you launch the app via the terminal and post the logs when you go through controller mapping.

**Comment by jaconey** [comment] 2024-09-28 22:35
I did. The mapping is working fine in memory. But during start up, I do see this log "chiaki.gui: Error retrieving controller mapping  Mapping not available" 
Some logs: https://ctxt.io/2/AAC4UVMcFg
I don't know where it's saved.

**Comment by streetpea** [comment] 2024-09-28 22:57
@jaconey what are the logs when opening chiaki-ng after closing?

**Comment by streetpea** [comment] 2024-09-28 23:04
@jaconey please export your settings file in config export settings and then show me the controller mapping array in that file.

**Comment by jaconey** [comment] 2024-09-29 00:11
> @jaconey what are the logs when opening chiaki-ng after closing?

```
chiaki.gui: [libplacebo]     External API interop:
chiaki.gui: [libplacebo]       UUID: 00:00:10:6B:0F:00:03:F0:00:00:00:00:00:00:00:00
chiaki.gui: [libplacebo]       PCI: 0000:00:00:0
chiaki.gui: [libplacebo]       buf export caps: 0x0
chiaki.gui: [libplacebo]       buf import caps: 0x10
chiaki.gui: [libplacebo]       tex export caps: 0x0
chiaki.gui: [libplacebo]       tex import caps: 0x70
chiaki.gui: [libplacebo]       sync export caps: 0x0
chiaki.gui: [libplacebo]       sync import caps: 0x0
[I] Discovery failed to bind port 9304, trying one higher
[E] Discovery failed to send: No route to host
[E] Discovery Service failed to send ping for PS4
[E] Discovery failed to send: No route to host
[E] Discovery Service failed to send ping for PS5
chiaki.gui: Error retrieving controller mapping  Mapping not available
dbus[378]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
```

**Comment by jaconey** [comment] 2024-09-29 00:13
> @jaconey please export your settings file in config export settings and then show me the controller mapping array in that file.

```
[controller_mappings]
1\controller_mapping="050095acac05000004000000fd216d04,8BitDo Pro 2,a:b3,b:b2,back:b6,crc:ac95,dpdown:b9,dpleft:b10,dpright:b11,dpup:b12,guide:b4,leftshoulder:b13,leftstick:b14,lefttrigger:+a2,leftx:a0,lefty:a1~,platform:Mac OS X,rightshoulder:b16,rightstick:b17,righttrigger:+a5,rightx:a3,righty:a4~,start:b5,x:b8,y:b7"
1\guid=050095acac05000004000000fd216d04
size=1
```

**Comment by streetpea** [comment] 2024-09-29 00:31
@jaconey to confirm you are using the controller in the same mode in both cases. There are separate mappings for Bluetooth and usb connections

**Comment by jaconey** [comment] 2024-09-29 00:39
Yes. I don't use the wired mode. I use BT all the time. I can repro just: open the app, change mapping, quit, open again

**Comment by streetpea** [comment] 2024-09-29 00:56
Unfortunately I can reproduce with any of my controllers but I’m looking into it

**Comment by streetpea** [comment] 2024-09-29 01:30
@jaconey can you try this build https://github.com/streetpea/chiaki-ng/actions/runs/11088504579/artifacts/1991531636?

**Comment by jaconey** [comment] 2024-09-29 02:01
Thanks! This one works!

**Comment by streetpea** [comment] 2024-09-29 02:36
Fixed by 6028156d7e4f2f8121df0880c40e57d210cf39f5

**Closed by streetpea** 2024-09-29 02:36 UTC

**Comment by streetpea** [comment] 2024-09-29 03:17
@jaconey btw what was happening is for certain controllers the controller mapping isn’t loaded into sdl unless the controller is attached. The controllers I was testing with didn’t have this issue. It just depends on the controller apparently. Anyway, I was loading the original controller mappings for the reset controller mapping function at the beginning of the session and if an original mapping wasn’t found to reset to I was not applying the mapping. This will fail if the controller isn’t connected when the program starts either because the controller takes a while to attach in SDL or it just isn’t connected initially. 

Now, that I realized that some mappings are only loaded when the controller is plugged in, I grab the original mapping and load the mapping only if the controller is attached and reload mappings when new controllers are mapped fixing the issue.

**Comment by jaconey** [comment] 2024-09-29 04:31
@streetpea  Thanks for the fix and the explanation! Looking at 6028156, all makes sense to me. I can confirm that now I can see the new log "Updated controller mapping for guid:" when I start Chiaki,  instead of the SDL error "Mapping not available". 

> some mappings are only loaded when the controller is plugged in

It's interesting that this is not the case for me. The controller is connected via BT all the time, but for some reason it's not loaded at the start time. 

Again really appreciate you help! I've been using Chiaki and very sad that it's not maintained anymore. I'm so grateful that you pick it up and started `chiaki-ng`! Amazing work!

**Comment by streetpea** [comment] 2024-09-29 04:55
So @jaconey it must be the 2nd case (the controller takes a while to load initially) so isn’t attached at program start (it’s attached slightly after).

**Comment by jaconey** [comment] 2024-10-02 20:30
@streetpea while testing the build you provided, I note something odd in one scenario, say:
1. I boot the controller and open chiaki-ng and play a game. Everything is perfect! 
2. I leave the app and the controller there. The controller will turn itself off after some time. App is still running
3. When I'm back, the app will register both settings, i.e. X is supposed to map O, but now it's a X+O, both "cancel" and "confirm", which makes it impossible to get back to the back :D 
4. The workaround for now is restart the session or restart the app then it fixes itself. 

Not block, but just find it a bit odd

**Comment by streetpea** [comment] 2024-10-04 00:25
@jaconey can you try this build https://github.com/streetpea/chiaki-ng/actions/runs/11171521741/artifacts/2013606258 and see if it fixes your problem?

**Comment by jaconey** [comment] 2024-10-04 03:06
@streetpea this version seems regressed. I lost the config again

**Comment by streetpea** [comment] 2024-10-04 03:22
@jaconey does it display anything in the terminal when launching via there?

**Comment by streetpea** [comment] 2024-10-04 15:37
@jaconey hard to tell without the terminal logs but potentially you have some other software interfering and updating your controller mapping database. Are you running chiaki-ng via Steam or have some sort of controller mapping software running on your Mac?

**Comment by jaconey** [comment] 2024-10-05 00:20
@streetpea This one is indeed interesting. From CLI log:

```
[I] Controller 1 opened: "8BitDo Pro 2 (050095acac05000004000000fd216d04)"
[I] Updated controller mapping for guid: 050095acac05000004000000fd216d04
[I] Controller 0 opened: "8BitDo Pro 2 (030095acc82d00000660000000010000)"
[I] Updated controller mapping for guid: 030095acc82d00000660000000010000
```

I somehow see two guid. I used to only see the 0500 one in the last build. 

FWIW, I do have Karabiner installed for mapping my keyboard. Not sure if related, but I check that it doesn't monitor/change any events from there.

**Comment by streetpea** [comment] 2024-10-05 01:56
@jaconey try this build https://github.com/streetpea/chiaki-ng/actions/runs/11189391375/artifacts/2018331795. I changed to using vidpid instead of guid for the mappings (applying one mapping for a given vendor id/ product id) so the mapping is portable across platforms. Maybe this will fix your issue.

**Comment by jaconey** [comment] 2024-10-05 03:15
thx! this one works. so far so good!

**Comment by streetpea** [comment] 2024-10-12 04:20
@jaconey any updates on this (I.e., did you run into the problem with the mapping going wonky when the controller turned off and back on like you were before?)
