### ISSUE TITLE
support windows on arm

### ISSUE THREAD

**Issue by shaoya730** [streetpea/chiaki-ng#401] opened 2024-09-07 05:39 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by streetpea** [comment] 2024-09-07 20:21
@shaoya730 can you provide a link to any resources to make arm windows builds. Arm windows is barely supported afaik and github actions doesn’t have windows arm hosts. Also I don’t think all of the dependencies are compiled for windows arm. There are currently Mac and Linux arm builds with the Mac build linked the releases and the Linux build available via flathub if you use those platforms on your arm computer.

**Comment by streetpea** [comment] 2024-09-07 20:30
@shaoya730 You can always build on arm yourself  by downloading msys2 opening the mingw64 shell and following the recipe in https://github.com/streetpea/chiaki-ng/blob/main/.github/workflows/build-msys2.yml

**Comment by streetpea** [comment] 2024-09-08 17:18
Closing this issue bc it’s a duplicate of #258

**Closed by streetpea** 2024-09-08 17:18 UTC
