### ISSUE TITLE
No Video output on DELL Hardware

### ISSUE THREAD

**Issue by DaveeMcKane** [streetpea/chiaki-ng#92] opened 2023-11-12 09:54 UTC
Hi Streetpea, thanks for your active develpment of Chiaki. No matter which versoin of Chiaki (official or forks) i use, when i connect to PS4 there no video output, while audio and navigation via keyboard works great. Also official PS Remote Play works with no problem on my pc.
Here is Log (since it was long, used anon notepad):
https://quicknote.io/2c36a4a0-8141-11ee-98c5-f9f8c49a37d3
Can you please fix the issue?

**Comment by streetpea** [comment] 2023-11-13 01:28
@DaveeMcKane it looks like you're getting frames and your frame buffer is filling up and staying stuffed. Perhaps the frames are never getting pulled from the buffer. Which version of chiaki4deck are you using?

**Comment by DaveeMcKane** [comment] 2023-11-13 16:07
@streetpea Thanks for reply, I'm using latest version 1.4.1, also this happens when using jbg77's chiaki, the official one will crash some seconds after connecting.
I tried all hardware decoding option, some give me error that doesn't exist before connecting,  two working ones "d3d11va" and "none" will give mentioned log results

**Comment by DaveeMcKane** [comment] 2023-11-19 06:17
@streetpea Would you consider fix this?

**Comment by streetpea** [comment] 2023-11-22 22:43
@DaveeMcKane are you playing a game locally on the PS5 or on the home menu when this occurs? (a black screen will be displayed if you try playing media content or streaming a PlayStation game via PS Plus during remote play). Is there any message on your PlayStation when you start streaming the content? I'm a bit at a loss as to what's happening on your end based on the logs. It seems like remote play is initialized and running and I don't see any errors from ffmpeg indicating something has gone wrong with decoding the video stream or from Qt indicating there is a problem displaying the content.

**Comment by DaveeMcKane** [comment] 2023-11-24 17:38
@streetpea I'm remote play locally connect a PS4 to my PC with a LAN cable, No internet. I turned off HDCP mode, and absolutely no banned content, since official remote play would connect and give video out without any problem.
I have this problem with all versions of Chiaki Windows on my Laptop(Official/4deck and other forks), while Chiaki android works perfectly on current setup (local connect).

Is it something to do with graphic card? If there was a directx 9 in video decoding options would it be working?

Also the normal "username connect via remote play" is shown just like connecting with a android phone

**Comment by streetpea** [comment] 2023-11-30 03:12
Hmm, since you are able to get decode the frames and they're sitting in the buffer it seems like the problem is with the OpenGL window displaying the content. Since the avopenglwidget is baked into qt I think the problem is there and not directly related to Chiaki. There is work ongoing to add a Vulkan renderer to chiaki4deck so it's possible that window will work for you on your device (see #93) but that's not going to be available for Windows initially.

**Comment by streetpea** [comment] 2024-01-20 02:35
@DaveeMcKane can you try the latest release. We switched to using Vulkan so perhaps it works now on your pc

**Comment by streetpea** [comment] 2024-02-15 00:25
@DaveeMcKane have you tried it yet?

**Comment by streetpea** [comment] 2024-09-08 17:46
@DaveeMcKane I’m closing this since I assume it works now with the new renderer since you haven’t responded in 8 months

**Closed** 2024-09-08 17:47 UTC
