### ISSUE TITLE
[Feature Request] Have a checkbox that allows you close the GUI when escaping from console

### ISSUE THREAD

**Issue by Jayinem** [streetpea/chiaki-ng#443] opened 2024-10-19 09:37 UTC
Using the --profile feature and autoconnect, with the addition of autohotkey scripts I've set it up where I can launch a console of my choice with just a keyboard key. It would be awesome if there was an option to not have the GUI come back up after I close the console, since I don't need the GUI at all unless I need to change a setting. 

However I see the issue what if I needed to change a setting and it's all set to autoconnect I wouldn't be able to. Maybe either some type of keyboard shortcut or a separate .exe that only changes settings, but does not have the choice of other profiles.

**Comment by streetpea** [comment] 2024-10-19 15:46
@Jayinem without the gui coming up there is no way to access the settings. This becomes a problem if you want to change the settings or access autoconnect.

**Comment by streetpea** [comment] 2024-10-19 16:29
@Jayinem after thinking about it a little more I can add an argument for closing the app automatically via the command line. Then you could create a different shortcut without that argument or modify the shortcut as needed to access the settings

**Comment by Jayinem** [comment] 2024-10-19 16:54
Thanks, yeah cause it's kind of a mess right now I'm accidentally turning on my other consoles while just controlling the one I want to control since you can use controller on the GUI.

**Comment by streetpea** [comment] 2024-10-19 23:17
Added --exit-app-on-stream-exit command to command line options which will close the GUI once you close the stream. Not sure what you mean by giving an option to run one console at a time. That is already an option in chiaki-ng. Just select a console and launch it If you want you can also make a profile with one console only registered.

**Comment by Jayinem** [comment] 2024-10-20 00:01
Sorry I get confused.

I tried adding--exit-app-on-stream-exit but it gave me an error 

chiaki: unknown option 'exit-app-on-stream-exit" this is my entire path 

C:\Users\Jayinem\Documents\PS4\chiaki-ng-win_x64-VC-Release\chiaki.exe --profile=PS5 --exit-app-on-stream-exit

Or does this need to be implemented on the next chiaki-ng version that's not out yet?

**Comment by streetpea** [comment] 2024-10-20 00:16
@Jayinem did you use the build that added it?

**Closed** 2024-10-20 00:18 UTC

**Comment by Jayinem** [comment] 2024-10-20 00:23
I'm getting it now but one last thing.

I made 3 different folders one for each console, but when I go to consoles and delete the other 2 consoles that are there they still show up in the main screen even after deleting them they just show unregistered. How do I completely remove them?

**Comment by streetpea** [comment] 2024-10-20 00:26
You can choose to hide the console in the menu

**Comment by Jayinem** [comment] 2024-10-20 00:35
I got that but I'm having second thoughts on using --exit-app-on-stream-exit, the reason is for PS4 many times they don't connect on the first try only wake up the console but then I have to use the gui to select it a second time for it to actually load, I don't have this issue on PS5.

If I can have 3 separate chiakis one in each folder it might be ok for the gui to come back but I would want only the one console in the GUI hopefully. I'm not sure why I can't remove the other consoles.

I looked in appdata/roaming and there's only some logs, where is chiaki being stored that it's keeping up because i go to different folders and make a change and it remembers what I did from the other folder and has the wrong profile.

**Comment by streetpea** [comment] 2024-10-20 00:38
@Jayinem you need to hide the other consoles

**Comment by streetpea** [comment] 2024-10-20 00:40
If you highlight the given unregistered console the option to hide it will appear

**Comment by Jayinem** [comment] 2024-10-20 00:41
Ok got it i missed that, I think I'm all set. Thank you very much.

**Comment by streetpea** [comment] 2024-10-20 00:51
I can update it to not quit on error if that helps, but it should retry on error

**Comment by Jayinem** [comment] 2024-10-20 02:04
Strangely it's not doing it anymore all of my consoles are connecting on the first try now, and I looked at the logs they're all from the last few minutes it was happening a few hours ago so I wouldn't be able to post them when they were doing it. 

I wonder if my GUI is showing up too big for my screen because I'm not seeing a hide button when I select a console, but since I made 3 different folders one for each console and am using your new build with the --exit-app-on-stream-exit command it's not as big of a deal anymore, only if it doesn't connect to the console will it show the GUI but mostly it's working.

**Comment by streetpea** [comment] 2024-10-20 04:17
@Jayinem my bad, the hide consoles feature wasn't in the build I gave you. Try this build: https://github.com/streetpea/chiaki-ng/actions/runs/11423276566/artifacts/2078555114 hide should be an option now when you highlight a given unregistered console.

**Comment by Jayinem** [comment] 2024-10-20 15:37
Ok I'll do that and just thought I'd let you know I just got timed out waiting for console, but it worked 2nd time.

[2024-10-20 10:34:31:645645] [I] Logging to file C:/Users/Jayinem/AppData/Roaming/Chiaki/Chiaki/log/chiaki_session_2024-10-20_10-34-31-640640.log
[2024-10-20 10:34:31:645645] [I] Chiaki Version 1.9.0
[2024-10-20 10:34:31:681681] [I] Trying to use hardware decoder "vulkan"
[2024-10-20 10:34:31:681681] [I] Using hardware decoder "vulkan" with pix_fmt=vulkan
[2024-10-20 10:34:31:689689] [I] ChiakiOpusEncoder initialized
[2024-10-20 10:34:31:690690] [I] Controller 0 opened: "Controller (MAGIC-NS) (0300bcb979000000d318000000007200)"
[2024-10-20 10:34:31:723723] [I] [libplacebo] Available surface configurations:
[2024-10-20 10:34:31:724724] [I] [libplacebo]     0: VK_FORMAT_B8G8R8A8_UNORM                 VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
[2024-10-20 10:34:31:724724] [I] [libplacebo]     1: VK_FORMAT_B8G8R8A8_SRGB                  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
[2024-10-20 10:34:31:724724] [I] [libplacebo]     2: VK_FORMAT_R8G8B8A8_UNORM                 VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
[2024-10-20 10:34:31:724724] [I] [libplacebo]     3: VK_FORMAT_R8G8B8A8_SRGB                  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
[2024-10-20 10:34:31:724724] [I] [libplacebo]     4: VK_FORMAT_A2B10G10R10_UNORM_PACK32       VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
[2024-10-20 10:34:31:724724] [I] [libplacebo] Picked surface configuration 4: VK_FORMAT_A2B10G10R10_UNORM_PACK32 + VK_COLOR_SPACE_SRGB_NONLINEAR_KHR

**Comment by Jayinem** [comment] 2024-10-20 15:48
Can you tell me why when I make changes to one folder it make changes to the other folders without me doing anything? I have a folder on one of my PS4s I tried hiding PS5 and another PS4, but when I open PS5 now I can't find PS5. It's not even there in consoles. And it seemed to change my default.ini. Is there a central location where these changes are being made? I don't see anything in appdata roaming just logs.

**Comment by Jayinem** [comment] 2024-10-20 16:00
Look at this 3 consoles that are ready
![Untitled](https://github.com/user-attachments/assets/d9e1585c-183a-4ce0-a209-626d2de31688)

But under consoles, 0 show up

![Untitled2](https://github.com/user-attachments/assets/b14494d0-de54-4c79-b354-7012cca930b6)

**Comment by streetpea** [comment] 2024-10-20 16:00
For windows settings are stored in the windows registry and each profile has its own registry entry .. you can see them with windows registry editor (there are no files locally on your computer)

**Comment by streetpea** [comment] 2024-10-20 16:02
@Jayinem Do the registered consoles show up with the old build?

**Comment by streetpea** [comment] 2024-10-20 16:02
@Jayinem I’ll look into it

**Comment by Jayinem** [comment] 2024-10-20 16:04
Also hide does not always work. 

No problem I'll wait.

**Comment by streetpea** [comment] 2024-10-22 03:05
@Jayinem it was a regression with the latest build I gave you. It's fixed here: https://github.com/streetpea/chiaki-ng/actions/runs/11452325499/artifacts/2085763488

**Comment by Jayinem** [comment] 2024-10-23 06:06
It's still screwed up because of using the registry and maybe you can't do anything about that I don't know but as I mentioned i made 3 different folders I wanted to keep all 3 consoles separated where there's just one registered console for each folder but because you do it in the registry I went in and started deleting profiles and now all my consoles are unregistered and they show up in the main screen but not in consoles just like the pics I showed before. This is with the new build you gave me.

**Comment by streetpea** [comment] 2024-10-23 06:09
@Jayinem using profiles separates them .. each profile has separate registry entries

**Comment by streetpea** [comment] 2024-10-23 06:15
It seems to work fine on my Steam Deck. I’ll try on a windows pc and get back to you.

**Comment by streetpea** [comment] 2024-10-23 06:34
@Jayinem I’ll set it up on my pc as you described and get it working on Windows. Then I’ll get back to you.

**Comment by streetpea** [comment] 2024-10-23 10:23
@Jayinem I was successful on my Windows 11 PC. I also found a few small bugs that I fixed in this build so please use this one: https://github.com/streetpea/chiaki-ng/actions/runs/11477762312/artifacts/2092840133

Since you mentioned having an ini file with all of your consoles registered, I started with that.
Then I made a copy of the ini file called profile1 and changed the this_profile setting from `this_profile=` (since it was the default profile I originally exported) to `this_profile=profile1` (the new profile I wanted to import). I then imported profile1. Next, I changed the profile 1 file to make `this_profile=PS5` and imported the PS5 profile. My Windows registry now looked like the following 
![WindowsRegistryChiakiProfiles](https://github.com/user-attachments/assets/75085f0b-3e80-460b-92d3-49a2ccdc171b) with separate folders for each profile. Next, I changed the registered consoles on one profile and it didn't affect the other profiles. I then hid 2 consoles and they didn't show up anymore in discovery until I unhid them. I did find a bug though where focus would be lost and so the controller wouldn't be able to select the next entry. Maybe you didn't notice focus had been lost and you were trying to hide with a controller but it wasn't actually selected so it wasn't working. You can tell it doesn't have focus if when you are looking at the entry it says Hide but doesn't have the square button symbol next to it that you would use a controller for. It worked fine with a mouse on the old build but I fixed it in the new build so it works with a controller as well. Hopefully you can replicate this on your PC

**Comment by Jayinem** [comment] 2024-10-23 15:08
No it wasn't hiding it, I had focus I was moving with the controller between profiles, that's not what happened.

But I just went back to the previous build without hiding because it's just causing me more issues than necessary. With this I am able to just run shortcuts and it doesn't matter if the other consoles aren't hidden. I was able to restore my previous consoles as well with this.  I've tried multiple times now but every time I tried to start unregistering consoles I had issues. I'm not going to continue to try.

I have one more question is there any way to take my PS5 offline yet still connect to Chiaki? Like with a certain DNS or anything? I am getting update nags and don't want to update my PS5.

**Comment by streetpea** [comment] 2024-10-23 16:01
@Jayinem i can guarantee you are not using the profiles correctly and that is the root of your problem. If you follow the instructions I provided it will as I tested it on my windows pc. Not sure about the hide not working though.

**Comment by streetpea** [comment] 2024-10-23 16:10
Just to clarify, as in the picture, each profile has its own folder in the registry so changing settings in one can’t effect a different profile because its settings exist in a different profile. What you’re describing with the console being deleted from the other profiles is impossible if it’s set up correctly. This implies it’s not set up correctly because changing one registry value in a different folder doesn’t affect the registry value in another folder because they are distinct values. I think I am doing a poor job of explaining myself but maybe that makes sense along with the picture I posted above.

**Comment by streetpea** [comment] 2024-10-23 16:14
If you send me a video of what you’re describing happening at streetpea@proton.me then I can tell you where you’re going wrong. Otherwise, I fear we will just talk in circles.

**Comment by Jayinem** [comment] 2024-10-23 20:47
Alright I'll try again later this evening with the latest build and update.

**Comment by streetpea** [comment] 2024-10-23 21:02
Ok just try to go through and if it doesn't work lmk but I don't want you to continue wasting time on it bc I know that can be frustrating. To make sure you are in the right profile and everything you can always look at the title window which will say Chiaki-ng:profile_name or Chiaki-ng if on the default profile. The hide thing seems to definitely be a different bug based on what you were describing that for some reason doesn't happen with the ps5s I tried to hide but just make sure the build doesn't fix it anyway. I would like to fix it if there is an issue with it but as you mentioned for your use case it's probably not that important if you are just using autoconnect and quitting after stream or on stream failure bc in that case you should never see the gui
