### ISSUE TITLE
[BUG]Controller will not stop vibrating when playing Spider-Man 2

### ISSUE THREAD

**Issue by Soxspark** [streetpea/chiaki-ng#504] opened 2024-12-14 13:41 UTC
**Describe the bug**
This has been an ongoing bug for multiple versions, and I’ve only ever seen it happen specifically with Spider-Man 2. I play with a DualSense connected via Bluetooth, and whenever I play Spider-Man 2, as soon as I web swing for the first time, the controller will vibrate endlessly until I close the game. The next game I open will work normally. 

**To Reproduce**
1. Play Spider-Man 2 with a dualsense controller connected. 
2. Move around. 
3. The controller will vibrate endlessly. 

**Expected behavior**
The controller should only vibrate when in combat/swinging I believe. I game 90% of the time through remote play these days. 

 - OS: MacOS
 - Version 15.2
 - Device: MacBook Pro (M3)
 - chiaki-ng Version 1.9.3

**Comment by Soxspark** [comment] 2024-12-14 14:03
Just for reference the controller _is_ being used wirelessly. I prefer using Chiaki over the official application, but the official app does have all functions working as expected with the controller connected via Bluetooth.

**Comment by streetpea** [comment] 2024-12-14 18:27
@Soxspark in the settings turn haptic rumble to off.

**Comment by Soxspark** [comment] 2024-12-14 18:45
@streetpea Will that disable rumble in the game completely? I haven’t tried a wired connection yet but I was wondering if that would fix it and allow me to keep rumble on.

**Comment by streetpea** [comment] 2024-12-14 21:18
@Soxspark yes wired would fix it but you would need to enable haptics by following these simple steps on your mac: https://streetpea.github.io/chiaki-ng/setup/controlling/#enabling-dualsense-haptics-on-macos

**Comment by streetpea** [comment] 2024-12-14 21:19
@Soxspark basically only wired supports haptics on devices other than PS5 so you need to have it wired for haptics. Otherwise, it uses rumble emulation which isn't perfect + the DualSense has absolutely terrible regular rumble (because it's built to use haptics).

**Comment by streetpea** [comment] 2024-12-18 22:51
I'm closing this as it's not a bug but a limitation with rumble on the DualSense and I've provided options to not face this issue.

**Comment by streetpea** [comment] 2024-12-18 23:36
Actually, it would be good to ensure the rumble isn't endlessly coming from the controller without input (which would be an SDL bug) so I'm reopening this.

**Comment by Soxspark** [comment] 2024-12-18 23:56
@streetpea I think it is a result of how Insomniac incorporated haptics/rumble in the game. Literally every single thing that your character does in-game results in a rumble. Walking, swinging, gliding, pedestrians walking next to you. I think the rumble emulation over wireless was freaking out in an attempt to simulate it. 

When I plugged a controller in and set the speakers settings correctly everything was normal and I realized _just how much _ the game tries to use the DualSense.

**Comment by streetpea** [comment] 2024-12-19 00:16
Here is a build that will print when rumble is actually being sent by the game https://github.com/streetpea/chiaki-ng/actions/runs/12403275534/artifacts/2340617969 ... it is is just being sent continuously then we should close this but if for example the rumble isn't being sent and it's still rumbling endlessly then that would be some sort of bug: https://github.com/streetpea/chiaki-ng/actions/runs/12403275534/artifacts/2340617969 ... you can launch via the terminal to see the logs in real time by going to the folder where the app bundle is located and then launching under `Contents/MacOS/chiaki`

**Closed** 2024-12-27 18:23 UTC

**Comment by snowmobile2004** [comment] 2025-02-23 18:40
Can you create a build with that rumble debug logging for Windows? I am getting the constant rumble even on the PS5 home screen when connected via Bluetooth (doesnt happen when wired), so it seems to be a SDL bug. Seems to occur after playing a game for a short while, eventually the rumble will stop turning off and keep going constantly.
