### ISSUE TITLE
[BUG]open chiaki and connect the console first and then insert the controller, and the controller produces strange vibrations

### ISSUE THREAD

**Issue by qazwsdc** [streetpea/chiaki-ng#417] opened 2024-09-26 15:08 UTC
**Describe the bug**
When the controller is plugged in while the console is already connected, the controller will produce intermittent and abnormal vibrations when the game triggers the vibration effect

**To Reproduce**
1. connect to ps5 and don't plug in dualsense
2. then connect dualsense using USB
3. if game triggers vibration then issue happen

**Desktop (please complete the following information):**
 - OS: win11
 - chiaki-ng Version 1.9.0

**Additional context**
If connect the controller before open chiaki everything works fine

**Comment by streetpea** [comment] 2024-09-27 00:26
@qazwsdc I can't reproduce. Can you check the sound settings on your computer and make sure sound isn't getting pumped into your DualSense microphone in addition to the haptics. That could cause the weird vibrations you are experiencing.

**Comment by qazwsdc** [comment] 2024-09-27 01:16
@streetpea It must be triggered by a specific vibration.
do you have GTA？take a car can directly trigger this issue.
By the way,this bug also existed in previous chiaki versions.

**Comment by streetpea** [comment] 2024-09-27 01:19
Do you mean trigger vibrations or haptics?

**Comment by qazwsdc** [comment] 2024-09-27 01:22
@streetpea maybe haptic I'm not sure the difference between the two.

**Comment by streetpea** [comment] 2024-09-27 02:52
Are the triggers vibrating or just the base of the DualSense?

**Comment by qazwsdc** [comment] 2024-09-27 03:05
> Are the triggers vibrating or just the base of the DualSense?

the base

**Comment by streetpea** [comment] 2024-09-27 03:27
@qazwsdc can you please post a log of this happening with verbose logging enabled

**Comment by qazwsdc** [comment] 2024-09-27 03:34
@streetpea 
[2024-09-27 11:31:20:333333] [I] Controller 1 opened: "DualSense Edge Wireless Controller (0300e0274c050000f20d000000016800)"
[2024-09-27 11:31:21:334334] [W] DualSense features were enabled and a DualSense is connected, but could not find the DualSense audio device!
[2024-09-27 11:31:23:080080] [I] CTRL RECEIVED
[2024-09-27 11:31:23:080080] [I] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[2024-09-27 11:31:23:080080] [I]      0 00 00 00 00 00 fe 00 00                         ........        
[2024-09-27 11:31:23:080080] [I] Ctrl received Heartbeat, sending reply
[2024-09-27 11:31:28:080080] [I] CTRL RECEIVED
[2024-09-27 11:31:28:080080] [I] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[2024-09-27 11:31:28:080080] [I]      0 00 00 00 00 00 fe 00 00                         ........        
[2024-09-27 11:31:28:080080] [I] Ctrl received Heartbeat, sending reply
[2024-09-27 11:31:33:080080] [I] CTRL RECEIVED
[2024-09-27 11:31:33:080080] [I] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[2024-09-27 11:31:33:080080] [I]      0 00 00 00 00 00 fe 00 00                         ........        
[2024-09-27 11:31:33:080080] [I] Ctrl received Heartbeat, sending reply
[2024-09-27 11:31:38:079079] [I] CTRL RECEIVED
[2024-09-27 11:31:38:079079] [I] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[2024-09-27 11:31:38:079079] [I]      0 00 00 00 00 00 fe 00 00                         ........        
[2024-09-27 11:31:38:079079] [I] Ctrl received Heartbeat, sending reply
[2024-09-27 11:31:43:081081] [I] CTRL RECEIVED
[2024-09-27 11:31:43:081081] [I] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[2024-09-27 11:31:43:081081] [I]      0 00 00 00 00 00 fe 00 00                         ........        
[2024-09-27 11:31:43:081081] [I] Ctrl received Heartbeat, sending reply
[2024-09-27 11:31:48:080080] [I] CTRL RECEIVED
[2024-09-27 11:31:48:080080] [I] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[2024-09-27 11:31:48:080080] [I]      0 00 00 00 00 00 fe 00 00                         ........        
[2024-09-27 11:31:48:080080] [I] Ctrl received Heartbeat, sending reply
[2024-09-27 11:31:53:080080] [I] CTRL RECEIVED
[2024-09-27 11:31:53:080080] [I] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[2024-09-27 11:31:53:080080] [I]      0 00 00 00 00 00 fe 00 00                         ........        
[2024-09-27 11:31:53:080080] [I] Ctrl received Heartbeat, sending reply
[2024-09-27 11:31:58:080080] [I] CTRL RECEIVED
[2024-09-27 11:31:58:080080] [I] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[2024-09-27 11:31:58:080080] [I]      0 00 00 00 00 00 fe 00 00                         ........        
[2024-09-27 11:31:58:080080] [I] Ctrl received Heartbeat, sending reply
[2024-09-27 11:32:03:080080] [I] CTRL RECEIVED
[2024-09-27 11:32:03:080080] [I] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[2024-09-27 11:32:03:080080] [I]      0 00 00 00 00 00 fe 00 00                         ........        
[2024-09-27 11:32:03:080080] [I] Ctrl received Heartbeat, sending reply
[2024-09-27 11:32:06:159159] [I] StreamConnection is disconnecting
[2024-09-27 11:32:06:159159] [I] StreamConnection sending Disconnect
[2024-09-27 11:32:06:159159] [I] StreamConnection was requested to stop
[2024-09-27 11:32:06:160160] [I] StreamConnection closed takion
[2024-09-27 11:32:06:160160] [I] StreamConnection completed successfully
[2024-09-27 11:32:06:160160] [I] Ctrl requested to stop
[2024-09-27 11:32:06:160160] [I] Ctrl stopped
[2024-09-27 11:32:06:160160] [I] Session has quit

**Comment by streetpea** [comment] 2024-09-27 04:23
@qazwsdc haptics are not being enabled in the logs you posted because it can’t find the dualsense audio device. You say they are being enabled when you launch without hotplugging?

**Comment by qazwsdc** [comment] 2024-09-27 04:27
@streetpea yes.If plug in dualsense before open chiaki,everything is normal

**Comment by streetpea** [comment] 2024-09-27 04:37
@qazwsdc can you try the things I mentioned?

**Comment by streetpea** [comment] 2024-09-27 04:39
1. Go into settings and turn haptic rumble intensity to Off
2. If you have one try with a regular DualSense instead of a DualSense edge.

**Comment by qazwsdc** [comment] 2024-09-27 06:04
@streetpea yes you are right. the regular DualSense is normal.
So how to solve problem with DS edge ?

**Comment by streetpea** [comment] 2024-09-27 14:37
@qazwsdc can you try going in your sound settings and seeing how long it takes for the DualSense edge speaker to appear after plugging in the controller? It must be longer than 10s. I can change the value to add a new wait time for DualSense edge and then it should work.

**Comment by qazwsdc** [comment] 2024-09-27 14:45
@streetpea it's about 11 second.
I think 15 second is enough.
maybe you can set it to 15 and try

**Comment by streetpea** [comment] 2024-09-27 21:42
@qazwsdc actually I misspoke. It's currently set to 1 second for DualSense. You're saying it should be over 11 seconds for DualSense Edge or 1.1 seconds?

**Comment by streetpea** [comment] 2024-09-27 22:55
If it is actually less than 15seconds needed lmk so I can change it as the regular dualsense takes less than 1 second for its audio device become available. Anyway, you can try this build that sets the wait for DualSense edge to 15 seconds https://github.com/streetpea/chiaki-ng/actions/runs/11078154932/artifacts/1989517243

**Comment by qazwsdc** [comment] 2024-09-28 01:17
@streetpea it's 11s not 1.1s
the link is 404 error

**Comment by streetpea** [comment] 2024-09-28 01:21
@qazwsdc you must be signed into github to download the link

**Comment by qazwsdc** [comment] 2024-09-28 01:45
@streetpea perfect
this works fine for me.
thank you bro

**Comment by streetpea** [comment] 2024-09-28 02:27
Fixed by 40f8ea849ac9f7d784d36391eb3fe752b86f9a22

**Closed by streetpea** 2024-09-28 02:27 UTC
