### ISSUE TITLE
Allow the specification of alternate ports for non-local connections

### ISSUE THREAD

**Issue by fydo** [streetpea/chiaki-ng#391] opened 2024-08-16 03:03 UTC
**Is your feature request related to a problem? Please describe.**
Since there is some overlap on PS5 and PS4 ports, I can only ever have one set up for access when away from home.

**Describe the solution you'd like**
Having the ability to define a custom set of port numbers on a per-console basis would allow for connections to multiple consoles via the same IP. (Port forwarding would need to be set up, of course)

**Describe alternatives you've considered**
A carefully set up VPN might solve this issue but would introduce unnecessary overhead to the connection.

**Comment by streetpea** [comment] 2024-08-16 17:55
Duplicate of #242

**Comment by streetpea** [comment] 2024-08-16 17:56
Duplicate of #242

**Closed by streetpea** 2024-08-16 17:56 UTC

**Comment by streetpea** [comment] 2024-08-16 17:58
There is already an issue for this. Also you can try the remote connection via PSN which does not require port forwarding.
